import React from 'react'
import needforcode from '../../images/needforcode.png';
import './StudentProfile.css';
import axios from 'axios'
import { useSelector } from 'react-redux';
import AttendanceChart from '../../components/Charts/AttendanceChart';
import LineChart from '../../components/Charts/LineChart';
const StudentProfile = () => {
  const { user } = useSelector(state => state.user);
  console.log(user);

  return (
    <div className='flex'>
      <div className="form">
        <div className="image">
          <img src={needforcode} alt="photo" className="photo" />
          <div className="place">
            <h1 className="text1"> HI {user?.name}! </h1>
            <h2 className="text"> Sapid: {user?.sapid} </h2>
            <h2 className="text"> Studentid: {user?.studentid} </h2>
            <h2 className="text"> Email-ID: {user?.email} </h2>
            <h2 className="text"> Teams: {user?.teams} </h2>
          </div>
        </div>
        <div className='flex flex-col align-center justify-center text-center mt-20 '>
          <div><h2 className="text2">Attached below is your childs attendance!</h2></div>
          <div className="flex align-middle justify-center mt-5">
            <div>
              <AttendanceChart />
            </div>
          </div>
          <div><h3 className="text2">Autogenerated response : Be careful about your childs attendance</h3></div>
        </div>

      </div>
    </div>
  )
}

export default StudentProfile